# Generated by Django 5.0.4 on 2024-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
