# Generated by Django 5.0.4 on 2024-10-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='monthly_pay',
            new_name='monthly_pay_in_thousands',
        ),
    ]
