# Generated by Django 5.0.4 on 2024-10-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_rename_monthly_pay_job_monthly_pay_in_thousands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='monthly_pay_in_thousands',
            new_name='monthly_pay',
        ),
    ]
