# Generated by Django 5.0.4 on 2024-11-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
