# Generated by Django 5.0.4 on 2024-11-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_job_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_created',
        ),
    ]
