# Generated by Django 5.0.4 on 2024-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_remove_job_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote')], default='Full Time', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
