# Generated by Django 5.0.4 on 2024-11-14 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_alter_job_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 5, 44, 37, 728049, tzinfo=datetime.timezone.utc)),
        ),
    ]
