# Generated by Django 5.0.4 on 2024-11-14 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_job_desirable_skills_job_mandatory_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 6, 4, 2, 67393, tzinfo=datetime.timezone.utc)),
        ),
    ]
